baseURL = "https://mallocfail.com/"
languageCode = "en-us"
title = "mallocfail"
theme = "neopost"

[pagination]
  pagerSize = 12

[taxonomies]
  tag = "tags"
  author = "authors"

[params]
  description = "Cyber writeups, cloud mistakes, OSINT trails, and lab notes."
